version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "grpc-microservice"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_TABLE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
      SSL_ROOTCERT: ""
      OPTIONS: ""
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge